swagger: "2.0"
info:
  description: "This Specimen API synchronizes local nucleotide database with Genbank"
  version: "1.0.0"
  title: "MycoLab Specimens API"
  termsOfService: "https://mycolab.org/terms/"
  contact:
    email: "developers@mycolab.org"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: "blast.mycolab.org"
basePath: "/v1"
tags:
- name: "specimens"
  description: "Everything about MycoLab specimens"
  externalDocs:
    description: "Find out more"
    url: "https://mycolab.org/specimens"

schemes:
- "https"
- "http"

paths:
  /specimen:
    post:
      tags:
      - "specimen"
      summary: "Add a new specimen"
      description: ""
      # operationId: "api.SpecimenView.post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Specimen object"
        required: true
        schema:
          $ref: "#/definitions/Specimen"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "specimen"
      summary: "Update an existing specimen"
      description: ""
      # operationId: "api.SpecimenView.put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Specimen object"
        required: true
        schema:
          $ref: "#/definitions/Specimen"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Specimen not found"
        "405":
          description: "Validation exception"
  /specimen/{specimenId}:
    get:
      tags:
      - "specimen"
      summary: "Find specimen by ID"
      description: "Returns a single specimen"
      # operationId: "api.SpecimenView.get"
      produces:
      - "application/json"
      parameters:
      - name: "specimenId"
        in: "path"
        description: "ID of specimen to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Specimen"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Specimen not found"
    delete:
      tags:
      - "specimen"
      summary: "Deletes a specimen"
      description: ""
      # operationId: "api.SpecimenView.delete"
      produces:
      - "application/json"
      parameters:
      - name: "specimenId"
        in: "path"
        description: "Specimen id to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Sequence not found"
definitions:
#  Tag:
#    type: "object"
#    properties:
#      id:
#        type: "integer"
#        format: "int64"
#      name:
#        type: "string"
  Observations:
    type: "object"
    properties:
      inaturalist:
        type: "integer"
        example: 87342096
      mushroomobserver:
        type: "integer"
        example: 354593
  Taxonomy:
    type: "object"
    properties:
      life:
        type: "string"
        example: "Prokaryota"
      domain:
        type: "string"
        example: "Eukaryota"
      kingdom:
        type: "string"
        example: "Fungi"
      subkingdom:
        type: "string"
        example: "Dikarya"
      phylum:
        type: "string"
        example: "Ascomycota"
      subphylum:
        type: "string"
        example: "Pezizomycotina"
      class:
        type: "string"
        example: "Leotiomycetes"
      order:
        type: "string"
        example: "Rhytismatales"
      family:
        type: "string"
        example: "Cudoniaceae"
      genus:
        type: "string"
        example: "Cudonia"
      species:
        type: "string"
        example: "Confusa"
  Specimen:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "a8eba8c71ab9943734bbe744a61afacc"
      name:
        type: "string"
        example: "Cudonia Confusa"
      tube:
        type: "integer"
        example: 33
      gel:
        type: "integer"
        example: 10
      stage:
        type: "string"
        example: "A5"
      sequence:
        type: "string"
        example: "ACTAtGttGCCTtGGCAGGCTGGCAGCAGCCTGCCGGTGGACCTCAACTCTTGAATCTCTGCtGTCTGAGTACTATATAATAGTTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCTCTGGTATTCCAGGGGGCATGCCTGTTCGAGCGTCATTACAACCCTCACGCCTAGCGTGGTCTTGGGCTCGCCCTGTAGGGCCTGCCTCAAAGTCAGTGGCGGCGTCATCTGACCCCTAAGCGTAGTAACATACACCTCGCTTTTGGGCGCTGGATGGAGGCCTGCTATGAACCCCCCATTTTACAGGTTGACCTCGGATCAGGTAGGGATACCCGCTGAACTTAAG"
      taxonomy:
        $ref: "#/definitions/Taxonomy"
      observations:
        $ref: "#/definitions/Observations"
#      tags:
#        type: "array"
#        items:
#          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "Specimen status"
        enum:
        - "classified"
        - "unclassified"
externalDocs:
  description: "Find out more about MycoLab"
  url: "https://mycolab.org"